spring:
  application:
    name: PAYMENT
  datasource:
    url: jdbc:h2:file:./payment
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
server:
  port: 7070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
rabbitmq:
  queue:
    name: payment-queue
  exchange:
    name: payment-exchange
  routing:
    key: payment-routing-key

sms:
  service:
    base:
      url: http://SMS-SERVICE/api/v1/sms