spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthFilter
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthFilter
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**


server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
