spring:
  application:
    name: eureka-server
server:
  port: 8671
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8671/eureka